# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1802b8ab6cfeaf4ce9444676c2f7a5c44a15d633f575ae79626ead0a314cc9c7fe5a9bcf9e4dedc1feaad3bafebc26c59d4660ca57871a3c76614443f19bf3

test:
  secret_key_base: e80e4fc592219ad0a4add408fdb022b3ba7dea0021f02826d05a427435956cb88ab962864f927d4e4163894478b7c87f1dbc3bee2e998dd8a11469922355b662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
